os: linux
dist: xenial
language: php

addons:
  apt:
    packages:
      - ant

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - "nightly"

jobs:
  fast_finish: true
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION != "nightly" && $TRAVIS_PHP_VERSION != "8.0" ]]; then
      composer install --no-suggest --no-interaction
    else
      # Ignore platform requirements to allow PHPUnit to install on PHP 8.
      composer install --no-suggest --no-interaction --ignore-platform-reqs
    fi

script:
  - ant phplint
  - ant phpunit
